/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_images_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/recognize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recognize Image */
        post: operations["recognize_image_images_recognize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_recognize_image_images_recognize_post */
        Body_recognize_image_images_recognize_post: {
            /** File */
            file: string;
        };
        /** Body_upload_image_images_upload_post */
        Body_upload_image_images_upload_post: {
            /** File */
            file: string;
            /** Sys */
            sys: number;
            /** Dia */
            dia: number;
            /** Pul */
            pul: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Source
             * @enum {string}
             */
            source: "local_ocr" | "gemini" | "gemini_auto" | "manual" | "user_confirmed";
            /** Corrected By User */
            corrected_by_user: boolean;
            /** Device Model */
            device_model?: string | null;
            /** Ai Suggested Sys */
            ai_suggested_sys?: number | null;
            /** Ai Suggested Dia */
            ai_suggested_dia?: number | null;
            /** Ai Suggested Pul */
            ai_suggested_pul?: number | null;
            /** Notes */
            notes?: string | null;
            /** Ocr Meta */
            ocr_meta?: components["schemas"]["OcrMeta"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** RecognizeResponse */
        RecognizeResponse: {
            /** Sys */
            sys: number;
            /** Dia */
            dia: number;
            /** Pul */
            pul: number;
            /** Confidence */
            confidence: number;
            /** Elapsed Ms */
            elapsed_ms: number;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Filename */
            filename: string;
            /** Folder */
            folder: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** OcrConfidence */
        OcrConfidence: {
            /** Min */
            min: number;
            /** Mean */
            mean: number;
        };
        /** OcrInferenceMs */
        OcrInferenceMs: {
            /** Display */
            display: number;
            /** Digits */
            digits: number;
            /** Postprocess */
            postprocess: number;
        };
        /** OcrMeta */
        OcrMeta: {
            /**
             * Engine
             * @enum {string}
             */
            engine: "local" | "gemini" | "manual";
            /**
             * Model Version
             * @default null
             */
            model_version: string | null;
            /** @default null */
            inference_ms: components["schemas"]["OcrInferenceMs"] | null;
            /** @default null */
            confidence: components["schemas"]["OcrConfidence"] | null;
            /**
             * Fallback Reason
             * @default null
             */
            fallback_reason: ("low_confidence" | "no_display" | "wrong_row_count" | "user_requested") | null;
            /**
             * User Agent
             * @default null
             */
            user_agent: string | null;
            /**
             * Hw Concurrency
             * @default null
             */
            hw_concurrency: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    upload_image_images_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_images_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recognize_image_images_recognize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_recognize_image_images_recognize_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecognizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
